# Generated by Django 5.1.2 on 2024-12-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogprofile',
            name='disease',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dogprofile',
            name='medications',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kilograms', null=True),
        ),
    ]
