# Generated by Django 5.1.2 on 2024-12-23 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_dogprofile_disease_dogprofile_medications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calorie_goal', models.FloatField(blank=True, null=True)),
                ('recommended_foods', models.TextField(blank=True, null=True)),
                ('recommended_supplements', models.TextField(blank=True, null=True)),
                ('dog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plan', to='healthapp.dogprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_description', models.TextField()),
                ('calories', models.FloatField()),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to='healthapp.dogprofile')),
            ],
        ),
    ]
