# Generated by Django 5.1.2 on 2024-12-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0003_dietplan_meallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
